version: "2"
services:
    jupyterlab:
        build:
            context: ./containers/jupyter
            dockerfile: Dockerfile
        user: root
        ports:
            - "8888:8888"
        volumes:
            - "./work:/home/jovyan/work"
        environment:
            NB_UID: 500
            GRANT_SUDO: "yes"
        command: start.sh jupyter lab --NotebookApp.password=${JUPYTER_PASSWORD_SHA1}
